name: phase-out-icev-in-germany
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11
    - flake8=6.0.0
    - snakemake-minimal=7.19.1
variables:
    SNAKEMAKE_PROFILE: ./profiles/default
