# The right place for all your configuration values.
colours:
    - "#09306B"
    - "#2271B5"
    - "#6BAED6"
push-directory: "~/Library/CloudStorage/Dropbox/CS\\ survey\\ DE\\ 2021/3rd\\ submission\\ \\&\\ response\\ to\\ reviewers/analysis\\ results"
